name: Lint & Unit Test

on:
  push:
    branches:
      - main

jobs:
  ci_matrix:
    strategy:
      matrix:
        test_name: [test-partOne, test-partTwo, test-partThree]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Set up postgres
        run: docker compose up -d
      - name: Run Migrations
        run: npm run migrate:test
      - name: Run Test
        run: npm run ${{ matrix.test_name}}
