name: Lint & Unit Test

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Set up postgres
        run: docker compose up -d
      - name: Run Migrations
        run: npm run migrate:test
      - name: Run Test
        run: npm run test
